In [2]:
import numpy as np

## np.linspace np.arange 精度过高
> 在提取sif数据文件时，采用xarray提取特定经纬度数据，由于数据精度过高（3600,7200），使用np.arange和np.linspace计算机存储格式为多位小数，导致xarray无法准确定位出现报错，解决方法：使用round函数保留两位小数


In [1]:

longitude=np.linspace(-180,180,7200,endpoint=False)
latitude=np.linspace(90,-90,3600,endpoint=False)

lon=np.arange(90,-90,-0.05)

longitude.tolist()
lon.tolist()

longitude = np.array([round(i,2) for i in longitude])
latitude = np.array([round(i,2) for i in latitude])

longitude.tolist()

[-180.0,
 -179.95,
 -179.9,
 -179.85,
 -179.8,
 -179.75,
 -179.7,
 -179.65,
 -179.6,
 -179.55,
 -179.5,
 -179.45,
 -179.4,
 -179.35,
 -179.3,
 -179.25,
 -179.2,
 -179.15,
 -179.1,
 -179.05,
 -179.0,
 -178.95,
 -178.9,
 -178.85,
 -178.8,
 -178.75,
 -178.7,
 -178.65,
 -178.6,
 -178.55,
 -178.5,
 -178.45,
 -178.4,
 -178.35,
 -178.3,
 -178.25,
 -178.2,
 -178.15,
 -178.1,
 -178.05,
 -178.0,
 -177.95,
 -177.9,
 -177.85,
 -177.8,
 -177.75,
 -177.7,
 -177.65,
 -177.6,
 -177.55,
 -177.5,
 -177.45,
 -177.4,
 -177.35,
 -177.3,
 -177.25,
 -177.2,
 -177.15,
 -177.1,
 -177.05,
 -177.0,
 -176.95,
 -176.9,
 -176.85,
 -176.8,
 -176.75,
 -176.7,
 -176.65,
 -176.6,
 -176.55,
 -176.5,
 -176.45,
 -176.4,
 -176.35,
 -176.3,
 -176.25,
 -176.2,
 -176.15,
 -176.1,
 -176.05,
 -176.0,
 -175.95,
 -175.9,
 -175.85,
 -175.8,
 -175.75,
 -175.7,
 -175.65,
 -175.6,
 -175.55,
 -175.5,
 -175.45,
 -175.4,
 -175.35,
 -175.3,
 -175.25,
 -175.2,
 -175.15,
 -175.1,
 -175.05,
 -175.0,
 -174.95,
 -174.9,
 -174.85,
 -174.8,
 -1

## np.where() 两种用法
1. result = np.where(condition, x, y)
2. 省略上述x和y参数，可用于查找符合条件的参数位置
> np.place()已被弃用，一般用np.where()替代

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
mask = arr > 2
arr = np.where(mask, 10, arr)
print(arr)

[ 1  2 10 10 10]


## 数组掩码mask
> [CSDN masked array](https://blog.csdn.net/qq1195365047/article/details/88555611)
> 结合pd.cut()使用时，mask掉的值依然会参与分类

In [1]:
import numpy as np
import numpy.ma as ma

x = np.array([1,2,3,5,7,4,3,2,8,0])
x.dtype

mask = x < 5
mx = ma.array(x,mask=mask,fill_value=-20)

print(mask)
print(mx)
print(mx.filled())

ma = mx.data
ma

dtype('int32')

[ True  True  True False False  True  True  True False  True]
[-- -- -- 5 7 -- -- -- 8 --]
[-20 -20 -20   5   7 -20 -20 -20   8 -20]


array([1, 2, 3, 5, 7, 4, 3, 2, 8, 0])

## np.array np.asarray
> 在修改数据的时候，np.array为copy出来一个副本，np.asarray为修改数据源[CSDN](https://blog.csdn.net/xiaomifanhxx/article/details/82498176?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522165467098216781685390300%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=165467098216781685390300&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~baidu_landing_v2~default-2-82498176-null-null.142^v11^pc_search_result_control_group,157^v13^new_style2&utm_term=np.array%E5%92%8Cnp.asarray&spm=1018.2226.3001.4187)

In [8]:
a=np.array((1, 2, 3))
b=np.array((4, 5, 6))
c=np.array(a)
d=np.asarray(b)
a[0]=2
b[0]=2
print(a, b, c, d)

[2 2 3] [2 5 6] [1 2 3] [2 5 6]


In [9]:
a=np.array((1, 2, 3))
b=np.array((4, 5, 6))
c=np.array(a)
d=np.asarray(b)
a=a-1
b=b-1
print(a, b, c, d)

[0 1 2] [3 4 5] [1 2 3] [4 5 6]


## 数据合并，读取多年数据时常用
> np.hstack(水平) np.vstack(竖直) 

## np.random.choice 随机抽取一维数组
> [CSDN随机抽取数组](https://blog.csdn.net/a_cherry_blossoms/article/details/123439697?ops_request_misc=&request_id=&biz_id=102&utm_term=python%20%E5%A4%9A%E7%BB%B4%E6%95%B0%E7%BB%84%E9%9A%8F%E6%9C%BA%E6%8A%BD%E5%8F%96&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduweb~default-2-123439697.142^v20^rank_v33,157^v15^new_3&spm=1018.2226.3001.4187)

In [1]:
import numpy as np
import numpy.ma as ma

a = np.array([[1, 5], [3, 5], [5, 6], [7, 2], [5, 9]])

mask = a == 5
a = ma.masked_array(a, mask=mask)
a = a.filled(fill_value=-9999)

def choice():
    b = np.random.choice(a.shape[0], 5)
    c = np.random.choice(a.shape[1], 5)
    
    d = a[b, c]
    
    lat=[]
    lon=[]
    
    for i in range(len(d)):
        if d[i]==-9999:
            continue
        else:
            lat.append(b[i])
            lon.append(c[i])
            
    return lat, lon

lat, lon = choice()

## 判断缺测值 np.isnan().any()/all()
> numpy 顶层方法

In [11]:
x = np.array([1, 2, 3, 5, 7, 4, 3, 2, 8, 0], dtype='float32')
x[0:2] = np.nan
np.isnan(x)
np.isnan(x).any()
np.isnan(x).all()
x[~np.isnan(x)]

array([ True,  True, False, False, False, False, False, False, False,
       False])

True

False

array([3., 5., 7., 4., 3., 2., 8., 0.], dtype=float32)

## 筛选特定元素
[Python快速过滤Numpy数组中特定元素的方法](https://blog.csdn.net/u010158659/article/details/48575179?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522167901836016800197054418%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=167901836016800197054418&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-48575179-null-null.142^v74^pc_new_rank,201^v4^add_ask,239^v2^insert_chatgpt&utm_term=numpy%20过滤元素&spm=1018.2226.3001.4187)  
> ?????? and和&，or和|的区别  
可以用~取反

In [ ]:
a = np.arange(20).reshape(4,5)

##### 这样会变成一维数组
ind = a>5
b = a[ind]

In [ ]:
d = a.copy()
d[(d<3)|(d>10)]=200

In [ ]:
level = "(a<3)|(a>10)"

c = a.copy()
exec(f"c[{level}]=200")

## 保存数组
[Numpy数组的保存与读取](https://blog.csdn.net/u010089444/article/details/52738479?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522167972113616800184165740%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=167972113616800184165740&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-52738479-null-null.142^v76^pc_new_rank,201^v4^add_ask,239^v2^insert_chatgpt&utm_term=numpy%20%E4%BF%9D%E5%AD%98%E6%95%B0%E7%BB%84&spm=1018.2226.3001.4187)
> 单个数组保存用np.save(); 多个数组保存用np.savez()

In [ ]:
np.save("filename.npy",a)
b = np.load("filename.npy")

In [ ]:
np.savez('data',d1,d2,d3)

## np.reshape()
> 常用参数：order="C", order="F", 分别为C语言顺序和Fortran顺序

In [4]:
a = np.arange(1, 481).reshape(40, 12)

b = a.reshape(480, order="F")

c = b.reshape(12, 40)

c

array([[  1,  13,  25,  37,  49,  61,  73,  85,  97, 109, 121, 133, 145,
        157, 169, 181, 193, 205, 217, 229, 241, 253, 265, 277, 289, 301,
        313, 325, 337, 349, 361, 373, 385, 397, 409, 421, 433, 445, 457,
        469],
       [  2,  14,  26,  38,  50,  62,  74,  86,  98, 110, 122, 134, 146,
        158, 170, 182, 194, 206, 218, 230, 242, 254, 266, 278, 290, 302,
        314, 326, 338, 350, 362, 374, 386, 398, 410, 422, 434, 446, 458,
        470],
       [  3,  15,  27,  39,  51,  63,  75,  87,  99, 111, 123, 135, 147,
        159, 171, 183, 195, 207, 219, 231, 243, 255, 267, 279, 291, 303,
        315, 327, 339, 351, 363, 375, 387, 399, 411, 423, 435, 447, 459,
        471],
       [  4,  16,  28,  40,  52,  64,  76,  88, 100, 112, 124, 136, 148,
        160, 172, 184, 196, 208, 220, 232, 244, 256, 268, 280, 292, 304,
        316, 328, 340, 352, 364, 376, 388, 400, 412, 424, 436, 448, 460,
        472],
       [  5,  17,  29,  41,  53,  65,  77,  89, 101, 113, 125, 137, 

## 数组类型转换

In [ ]:
import numpy as np

# 创建一个示例数组
original_array = np.array([1.5, 2.7, 3.3, 4.8])

# 将数组转换为整数类型 (int)
integer_array = original_array.astype(np.int32)

# 将数组转换为无符号整数类型 (uint)
uint_array = original_array.astype(np.uint8)

# 将数组转换为浮点数类型 (float)
float_array = original_array.astype(np.float64)

# 输出不同数据类型的数组
print("Original Array:", original_array)
print("Integer Array:", integer_array)
print("Unsigned Integer Array:", uint_array)
print("Float Array:", float_array)


## numpy 数组元素的添加、插入和删除(array类型)
1. np.append() 在末尾添加元素
2. np.insert() 在任意位置添加元素
3. np.delete() 删除任意位置的元素

In [3]:
x = np.arange(9)
a = np.append(x, [10, 11])
b = np.insert(x, 3, [10, 11])
c = np.delete(x, [1, 2, 3])
x; a; b; c

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

array([ 0,  1,  2, 10, 11,  3,  4,  5,  6,  7,  8])

array([0, 4, 5, 6, 7, 8])

## np.repeat() 
> numpy.repeat(a, repeats, axis=None)

In [ ]:
import numpy as np

# 示例 1：重复一维数组中的元素
arr = np.array([1, 2, 3])
repeated = np.repeat(arr, 3)
print(repeated)
# 输出：[1 1 1 2 2 2 3 3 3]

# 示例 3：按轴重复
matrix = np.array([[1, 2], [3, 4]])
repeated = np.repeat(matrix, 3, axis=0)  # 沿行的方向重复
print(repeated)

# 示例 4：使用数组作为 repeats 参数
arr = np.array([1, 2, 3])
repeats = np.array([2, 3, 1])
repeated = np.repeat(arr, repeats)
print(repeated)
# 输出：[1 1 2 2 2 3]


### 用于升维后重复数组,在mask草地区域中运用
> lcc shape: (30, 50)

In [ ]:
def mask_array(func):
    data = func()
    # print(data.ndim)

    if data.ndim == 3:
        ## data(40, 30, 50)
        def mask():
            sp = data.shape[0]
            lcc2 = lcc.copy()
            np.place(lcc2, lcc2 != 130, 1)
            np.place(lcc2, lcc2 == 130, 0)
            lcc_mk = np.repeat(lcc2[np.newaxis, ], sp, axis=0)
            data_mk = np.ma.masked_array(data, mask=lcc_mk)
            data_mk_ave = np.nanmean(data_mk, axis=(1, 2))
            return data_mk_ave.data
    else:
        #### SM(40, 4, 30, 50)
        def mask():
            sp = data.shape[0]
            lcc2 = lcc.copy()
            np.place(lcc2, lcc2 != 130, 1)
            np.place(lcc2, lcc2 == 130, 0)
            lcc_mk = np.repeat(lcc2[np.newaxis, ], 4, axis=0)
            lcc_mk = np.repeat(lcc_mk[np.newaxis, ], sp, axis=0)
            # print(data.shape, lcc_mk.shape)
            data_mk = np.ma.masked_array(data, mask=lcc_mk)
            data_mk_ave = np.nanmean(data_mk, axis=(2, 3))
            return data_mk_ave.data

    return mask

## Difference between a=b & a=b.copy()
### data = data2 与 data = data2.copy() 的区别是？
> **data=data2**  
> 这是一种浅复制，修改其中一个变量的内容，另一个也会反映更改
> 该操作将data2变量简单地指向了data2所引用的对象，二者实际上引用相同的内存空间，因此它们是共享数据的  

> **data=data2.copy()**  
> 这是一种深复制（deep copy）操作。它会创建一个完全独立于原始对象的新对象，新对象的内容与原始对象相同;修改其中之 一不会影响另一个变量的内容

In [5]:
data2 = np.array([1, 2, 3])
data = data2  # 这只是创建了一个引用，没有复制数据
data[0] = 100
print(data2)  # 输出 [100, 2, 3]，因为两者引用相同的数据

result = (data is data2)
result

data2 = np.array([1, 2, 3])
data = data2.copy()  # 创建了一个新的独立复制
data[0] = 100
print(data2)  # 输出 [1, 2, 3]，因为它们是独立的对象

result = (data is data2)
result

[100   2   3]


True

[1 2 3]


False

### is运算符：判断两数组是否来自相同的数据空间

In [4]:
a = [1, 2, 3]
b = a  # b引用了a的对象

# 使用is运算符检查是否引用相同的对象
result = (a is b)
print(result)  # 输出 True，a和b引用同一个对象

c = [1, 2, 3]
# 使用is运算符检查c是否引用相同的对象
result = (c is a)
print(result)  # 输出 False，c和a引用不同的对象

True
False


### NaN值在任何情况下判断均不相等
> 在NumPy中，两个NaN值（Not-a-Number）之间的比较操作会返回False，因为NaN值在比较时被认为是不相等的。这是由于NaN表示一个未定义或不可表示的值，它与任何其他NaN值都不相等

In [6]:
a, b = np.nan, np.nan
a==b

False