[Rasterio官方文档 quick start](https://rasterio.readthedocs.io/en/latest/index.html)

In [1]:
import rasterio

In [2]:
dataset = rasterio.open('D:\study\Gosif_Data\GOSIF_2020001.tif')

RasterioIOError: D:/study/Gosif_Data/GOSIF_2020001.tif: No such file or directory

In [ ]:
dataset.count #bands

In [6]:
dataset.bounds 

BoundingBox(left=-180.0, bottom=-90.0, right=180.0, top=90.0)

In [7]:
dataset.driver

'GTiff'

In [8]:
dataset.transform

Affine(0.05, 0.0, -180.0,
       0.0, -0.05, 90.0)

In [10]:
# Data from a raster band can be accessed by the band’s index number. Following the GDAL convention, bands are indexed from 1.
dataset.indexes

(1,)

In [11]:
band1 = dataset.read(1)

In [12]:
print(band1.shape)

(3600, 7200)


In [13]:
print(band1)

[[32767 32767 32767 ... 32767 32767 32767]
 [32767 32767 32767 ... 32767 32767 32767]
 [32767 32767 32767 ... 32767 32767 32767]
 ...
 [32767 32767 32767 ... 32767 32767 32767]
 [32767 32767 32767 ... 32767 32767 32767]
 [32767 32767 32767 ... 32767 32767 32767]]


In [6]:
import rasterio

with rasterio.open('D:\study\Gosif_Data\GOSIF_2020.tif') as ds:
    print('该栅格数据的基本数据集信息（这些信息都是以数据集属性的形式表示的）：')
    print(f'数据格式：{ds.driver}')
    print(f'波段数目：{ds.count}')
    print(f'影像宽度：{ds.width}')
    print(f'影像高度：{ds.height}')
    print(f'地理范围：{ds.bounds}')
    print(f'反射变换参数（六参数模型）：\n {ds.transform}')
    print(f'投影定义：{ds.crs}')
    # 获取第一个波段数据，跟GDAL一样索引从1开始
    # 直接获得numpy.ndarray类型的二维数组表示，如果read()函数不加参数，则得到所有波段（第一个维度是波段）
    band1 = ds.read(1)
    print(f'第一波段的最大值：{band1.max()}')
    print(f'第一波段的最小值：{band1.min()}')
    print(f'第一波段的平均值：{band1.mean()}')
    # 根据地理坐标得到行列号
    x, y = (ds.bounds.left , ds.bounds.top )  # 距离左上角东300米，南300米的投影坐标
    row, col = ds.index(x, y)  # 对应的行列号
    print(f'(投影坐标{x}, {y})对应的行列号是({row}, {col})')
    # 根据行列号得到地理坐标
    x, y = ds.xy(row, col)  # 中心点的坐标
    print(f'行列号({row}, {col})对应的中心投影坐标是({x}, {y})')
    # 那么如何得到对应点左上角的信息
    x, y = (row, col) * ds.transform
    print(f'行列号({row}, {col})对应的左上角投影坐标是({x}, {y})')
    
    print('-------------------------------------------------')
    x2, y2 = (ds.bounds.right, ds.bounds.bottom)
    row2, col2 = ds.index(x2, y2)  # 对应的行列号
    x2, y2 = ds.xy(row2, col2)  # 中心点的坐标
    print(f'行列号({row2}, {col2})对应的中心投影坐标是({x2}, {y2})')

该栅格数据的基本数据集信息（这些信息都是以数据集属性的形式表示的）：
数据格式：GTiff
波段数目：1
影像宽度：7200
影像高度：3600
地理范围：BoundingBox(left=-180.0, bottom=-90.0, right=180.0, top=90.0)
反射变换参数（六参数模型）：
 | 0.05, 0.00,-180.00|
| 0.00,-0.05, 90.00|
| 0.00, 0.00, 1.00|
投影定义：EPSG:4326
第一波段的最大值：32767
第一波段的最小值：-647
第一波段的平均值：25700.157925655865
(投影坐标-180.0, 90.0)对应的行列号是(0, 0)
行列号(0, 0)对应的中心投影坐标是(-179.975, 89.975)
行列号(0, 0)对应的左上角投影坐标是(-180.0, 90.0)
-------------------------------------------------
行列号(3600, 7200)对应的中心投影坐标是(180.025, -90.025)


<ipython-input-6-03fc49e0a8cb>:26: DeprecationWarning: Right multiplication will be prohibited in version 3.0
  x, y = (row, col) * ds.transform
